
CREATE TABLE USER_TBL
(
    USER_ID INT IDENTITY(1,1) CONSTRAINT PKUSER PRIMARY KEY ,
    USERNAME VARCHAR(30) CONSTRAINT USERNAMEREQ NOT NULL,
    DOB DATE CONSTRAINT DOBREQ NOT NULL,
    GENDER VARCHAR(6) CONSTRAINT GENDER_REC NOT NULL,
    PHONE CHAR(11) CONSTRAINT PHONEREQ NOT NULL,
    EMAIL VARCHAR(40) CONSTRAINT EMAILREQ UNIQUE NOT NULL,
	CNIC CHAR(13) CONSTRAINT CNICREQ UNIQUE NOT NULL,
    CONSTRAINT CHECK_GEN CHECK(GENDER IN('Male','Female','Others'))
);


CREATE TABLE USER_TYPE
(
    USER_ID INT NOT NULL,
    U_TYPE VARCHAR(9) CONSTRAINT PKUSERTYPEREQ NOT NULL,
    CONSTRAINT PK_UTYPE PRIMARY KEY(USER_ID, U_TYPE),
    CONSTRAINT CHECK_UTYPE CHECK(U_TYPE IN ('SP', 'CONSUMER')),
    CONSTRAINT FK_UTYPE FOREIGN KEY(USER_ID) REFERENCES USER_TBL(USER_ID)
);

CREATE TABLE CONSUMER
(
    CONSUMER_ID INT CONSTRAINT PK_CONSUMER PRIMARY KEY,
    UTYPE VARCHAR(9) NOT NULL,
    CONSTRAINT FK_CONSUMER FOREIGN KEY(CONSUMER_ID, UTYPE) REFERENCES USER_TYPE(USER_ID, U_TYPE),
    CONSTRAINT CHECK_USER CHECK(UTYPE='CONSUMER')
);

CREATE TABLE CATEGORY
(
    CATEGORY_ID INT IDENTITY(1,1) CONSTRAINT PK_CATEGORY PRIMARY KEY  ,
    CATEGORY_NAME VARCHAR(30) NOT NULL,
);



CREATE TABLE SERVICES
(
    SERVICE_ID INT IDENTITY(1,1) PRIMARY KEY,
    SERVICENAME VARCHAR(50 ),
    CATEGORY_ID INT,
    CONSTRAINT FK_SERVICES FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

CREATE TABLE SERVICE_PROVIDER
(
    SP_ID INT CONSTRAINT PK_SP PRIMARY KEY,
    UTYPE VARCHAR(9),
	
   
   CONSTRAINT FK_SP_UT FOREIGN KEY(SP_ID, UTYPE) REFERENCES USER_TYPE(USER_ID, U_TYPE),
    CONSTRAINT CHECK_USER_SP CHECK(UTYPE='SP')
);

  
CREATE TABLE SERVICE_SP
(
    SP_ID INT,
    SERVICE_ID INT,
    DESCRIPTION_ VARCHAR(100)NOT NULL,
    PRICE DECIMAL(6,2) NOT NULL,
    DURATION DECIMAL(6,2) NOT NULL,
   
   CONSTRAINT PK_SSP_TBL PRIMARY KEY(SP_ID, SERVICE_ID),
    CONSTRAINT FK_SP_TBL FOREIGN KEY(SP_ID) REFERENCES SERVICE_PROVIDER(SP_ID),
    CONSTRAINT FK_SERVICE FOREIGN KEY(SERVICE_ID) REFERENCES SERVICES(SERVICE_ID)
);

CREATE TABLE MESSAGES
(
    MESSAGE_ID INT IDENTITY(1,1) PRIMARY KEY ,
    SENDER_ID INT,
    RECEIVER_ID INT,
    MSG_CONTENT VARCHAR(50) CONSTRAINT MESSAGEREQ NOT NULL,
    CONSTRAINT FK_SENDER FOREIGN KEY(SENDER_ID) REFERENCES USER_TBL(USER_ID),
    CONSTRAINT FK_RECEIVER FOREIGN KEY(RECEIVER_ID) REFERENCES USER_TBL(USER_ID),
    CONSTRAINT NOTSAME CHECK(SENDER_ID != RECEIVER_ID)
);

CREATE TABLE LOCATION_TBL
(
    LOCATION_ID INT IDENTITY(1,1) CONSTRAINT PK_LOCATION PRIMARY KEY,
    CITY VARCHAR(15),
    STATE_ VARCHAR(15),
    COUNTRY VARCHAR(15),
    AREA VARCHAR(35),
);

CREATE TABLE ADDRESS_TBL
(
	ADDRESS_ID INT IDENTITY(1,1) CONSTRAINT PK_ADDRESS PRIMARY KEY ,
	USER_ID INT,
	LOCATION_ID INT,
	ADDRESS VARCHAR(100) CONSTRAINT ADDREQ NOT NULL,
	CONSTRAINT FK_USER_TBL FOREIGN KEY(USER_ID) REFERENCES CONSUMER(CONSUMER_ID),
	CONSTRAINT FK_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION_TBL (LOCATION_ID),
);

CREATE TABLE BOOKING
(
    BOOKING_ID INT IDENTITY(1,1) CONSTRAINT PK_BOOKING PRIMARY KEY ,
	CONSUMER_ID INT,
	SP_ID INT,
	SERVICE_ID INT,
    BOOKING_DATE DATETIME CONSTRAINT BOOKINDREQ NOT NULL,
    SERVICE_DATE DATETIME CONSTRAINT SERVICEDREQ NOT NULL,
    STATUS_ VARCHAR(15) CONSTRAINT STATUSREQ NOT NULL,
	CONSTRAINT FK_CONSUMER_TBL FOREIGN KEY (CONSUMER_ID) REFERENCES CONSUMER(CONSUMER_ID),
	CONSTRAINT FK_SSP FOREIGN KEY (SP_ID,SERVICE_ID) REFERENCES SERVICE_SP(SP_ID,SERVICE_ID),
	CONSTRAINT STATUS_CHECK CHECK (STATUS_ IN ('BOOKED', 'CANCELLED','COMPLETED')),
);

CREATE TABLE PAYMENT
(
    PAYMENT_ID INT IDENTITY(1,1) CONSTRAINT PK_PAYMENT PRIMARY KEY ,
	CONSUMER_ID INT CONSTRAINT CONSUMERIDREQ NOT NULL,
	BOOKING_ID INT CONSTRAINT BOOKINGIDREQ NOT NULL,
    FARE DECIMAL(6,2) CONSTRAINT FAREREQ NOT NULL,
    PAYMENT_METHOD VARCHAR(15) CONSTRAINT PAYMETHODREQ NOT NULL,
	PAYMENT_DATE DATETIME CONSTRAINT PAYDATEREQ NOT NULL,
	PAYMENT_STATUS VARCHAR(15) CONSTRAINT PAYMENTSTATUSREQ NOT NULL,
	CONSTRAINT PAYMENT_STATUSCHECK CHECK(PAYMENT_STATUS IN ('PAID','PENDING','REFUNDED')),
	CONSTRAINT FK_CONSUMERTBL FOREIGN KEY (CONSUMER_ID) REFERENCES CONSUMER(CONSUMER_ID),
	CONSTRAINT FK_BOOKING FOREIGN KEY(BOOKING_ID) REFERENCES BOOKING(BOOKING_ID)

);
CREATE TABLE RATINGS
(
	BOOKING_ID INT IDENTITY (1,1)  CONSTRAINT PK_RATINGS PRIMARY KEY ,
	CONSUMER_ID INT CONSTRAINT CONSUMERIDREQ NOT NULL,
	SP_ID INT CONSTRAINT SPIDREQ NOT NULL,
	RATING_STARS INT CONSTRAINT RATINGSTARSREQ NOT NULL,
	COMMENTS VARCHAR(150),
	DATE_ DATETIME CONSTRAINT DATEREQ NOT NULL,
	CONSTRAINT FK_CONS FOREIGN KEY (CONSUMER_ID) REFERENCES CONSUMER (CONSUMER_ID),
	CONSTRAINT FK_SP_TB FOREIGN KEY (SP_ID) REFERENCES SERVICE_PROVIDER(SP_ID)

);

